[package]
name = "strumok_suppliers"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z' 
#lto = true
codegen-units = 1
strip = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies.reqwest]
version = "0.12.9"
default-features = false
features = [
    "charset",
    "http2",
    "rustls-tls",
    "rustls-tls-native-roots",
    # Compression
    "brotli",
    "gzip",
]

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
flutter_rust_bridge = "=2.6.0"
anyhow = "1.0.93"
enum_dispatch = "0.3.13"
strum = { version = "0.26.3", features = ["strum_macros"] }
strum_macros = "0.26.4"
serde_json = "1.0.132"
serde = { version = "1.0", features = ["derive"] }
scraper = "0.21.0"
regex = "1.11.1"
chrono = "0.4.38"


